- name: setup new machine
  hosts: all
  vars_files:
    - "vars/default.yaml"
    - "vars/{{ ansible_distribution | lower }}.yaml"

  pre_tasks:
    - name: Check supported distribution
      fail:
        msg: "Unsupported distribution: {{ ansible_distribution }}. Only Fedora and Ubuntu are supported."
      when: ansible_distribution not in ['Fedora', 'Ubuntu']

    - name: Update DNF and install Development Tools (Fedora)
      become: true
      when: ansible_distribution == 'Fedora'
      block:
        - name: Update DNF cache
          ansible.builtin.dnf:
            update_cache: true

        - name: Upgrade all packages
          ansible.builtin.dnf:
            name: "*"
            state: latest

        - name: Install RPM Fusion free repository
          ansible.builtin.dnf:
            name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
            state: present

        - name: Install RPM Fusion non-free repository
          ansible.builtin.dnf:
            name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
            state: present

        # - name: Install RPM Fusion repos
        #   community.general.dnf_config_manager:
        #     name: []
        #     state: enabled

        - name: Install Development Tools group
          ansible.builtin.dnf:
            skip_broken: true
            name: "@development-tools"
            state: present

    - name: Update APT cache and upgrade packages (Ubuntu)
      become: true
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: Update APT cache
          ansible.builtin.apt:
            update_cache: true

        - name: Upgrade all packages
          ansible.builtin.apt:
            upgrade: dist

  tasks:
    - import_tasks: ./tasks/1_core.yaml
    - import_tasks: ./tasks/2_langs.yaml
    - import_tasks: ./tasks/3_more_tools.yaml
    - import_tasks: ./tasks/4_dotfile.yaml
    - import_tasks: ./tasks/5_app.yaml
    - import_tasks: ./tasks/6_flatpak.yaml
