- name: Install Common Packages
  become: true
  package: "{{ item }}"
  loop: "{{ common_packages }}"
  tags:
    - install
    - core
    - common
    - dev

- name: Install Os specific Packages
  become: true
  package: "{{ item }}"
  loop: "{{ packages }}"
  tags:
    - install
    - core
    - specific
    - dev

- name: Install Tools
  become: true
  package: "{{ item }}"
  loop: "{{ tools.values() }}"
  tags:
    - install
    - core
    - tools
    - dev

#- name: Config Aliases
#  ansible.builtin.file:
#    src: "{{ item }}"
#    dest: "{{ aliases[item] }}"
#    state: link
#  loop: "{{ aliases.keys() | list }}"
#  tags:
#    - config
#    - core
#    - alias
#    - dev

- name: Install Neovim
  block:
    - name: Add Neovim PPA on Ubuntu
      apt_repository:
        repo: ppa:neovim-ppa/stable
      when: ansible_distribution == 'Ubuntu'

    - name: Install Neovim and dependencies on Ubuntu
      become: true
      package: "{{ item }}"
      loop:
        - software-properties-common
        - neovim
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
      when: ansible_distribution == 'Ubuntu'

    - name: Install Neovim on Fedora
      become: true
      package: "{{ item }}"
      loop:
        - neovim
        - python3-neovim
      when: ansible_distribution == 'Fedora'
