- name: Install Common Packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  tags:
    - install
    - core
    - common
    - dev

- name: Install OS specific Packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  tags:
    - install
    - core
    - specific
    - dev

- name: Install Tools
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ tools.values() }}"
  tags:
    - install
    - core
    - tools
    - dev

- name: Config Aliases
  ansible.builtin.file:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ aliases }}"
  tags:
    - config
    - core
    - alias
    - dev

- name: Install Neovim
  block:
    - name: Add Neovim PPA on Ubuntu
      apt_repository:
        repo: ppa:neovim-ppa/stable
      when: ansible_distribution == 'Ubuntu'

    - name: Install Neovim and dependencies on Ubuntu
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - software-properties-common
        - neovim
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
      when: ansible_distribution == 'Ubuntu'

    - name: Install Neovim on Fedora
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - neovim
        - python3-neovim
      when: ansible_distribution == 'Fedora'
