- name: Install Node.js (fnm)
  block:
    - name: Install dependencies
      become: true
      package:
        name: [curl, unzip]
        state: present

    - name: Install fnm
      shell: |
        curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/bin"

    - name: Install Node.js with fnm
      shell: |
        export PATH="{{ ansible_env.HOME }}/.local/share/fnm:$PATH"
        fnm install {{ nodeversion }}
        fnm use {{ nodeversion }}
        fnm default {{ nodeversion }}
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/share/fnm"
  tags:
    - install
    - dev

- name: Install Go
  become: true # Required for /usr/local installation
  tags:
    - install
    - dev
  block:
    - name: Remove existing Go installation
      file:
        path: /usr/local/go
        state: absent

    - name: Download Go tarball
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ goversion }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ goversion }}.linux-amd64.tar.gz"
        mode: "0644"

    - name: Download Go checksum
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ goversion }}.linux-amd64.tar.gz.sha256"
        dest: "/tmp/go{{ goversion }}.linux-amd64.tar.gz.sha256"
        mode: "0644"

    - name: Verify Go checksum
      ansible.builtin.shell: |
        cd /tmp
        sha256sum -c go{{ goversion }}.linux-amd64.tar.gz.sha256
      args:
        executable: /bin/bash

    - name: Extract Go archive
      ansible.builtin.unarchive:
        src: "/tmp/go{{ goversion }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes

- name: Install Rust
  tags:
    - install
    - dev
  block:
    - name: Check if Rust is already installed
      command: rustc --version
      register: rust_installed
      ignore_errors: true
      changed_when: false

    - name: Download and install Rust using rustup
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain {{ rustversion }} -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}"
      when: rust_installed.rc != 0

- name: Install Python (uv)
  block:
    - name: Install dependencies
      become: true
      package:
        name: [curl, python3, python3-pip]
        state: present

    - name: Install uv
      shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/uv" # Or wherever uv gets installed
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}"
  tags:
    - install
    - dev
