- name: Install Node.js (fnm)
  block:
    - name: Install dependencies
      become: true
      package:
        name: [curl, unzip]
        state: present

    - name: Install fnm
      shell: |
        curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/bin"
  tags:
    - install
    - langs
    - dev

- name: Install Go
  become: true
  tags:
    - install
    - langs
    - dev
  block:
    - name: Remove existing Go installation
      file:
        path: /usr/local/go
        state: absent

    - name: Download Go tarball
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ goversion }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ goversion }}.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Go archive
      ansible.builtin.unarchive:
        src: "/tmp/go{{ goversion }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes

- name: Install Rust
  tags:
    - install
    - langs
    - dev
  block:
    - name: Check if Rust is already installed
      command: rustc --version
      register: rust_installed
      ignore_errors: true
      changed_when: false

    - name: Download and install Rust using rustup
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}"
      when: rust_installed.rc != 0

- name: Install Python (uv)
  block:
    - name: Install dependencies
      become: true
      package:
        name: [curl, python3, python3-pip]
        state: present

    - name: Install uv
      shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/uv"  # Or wherever uv gets installed
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}"
  tags:
    - install
    - langs
    - dev
