- name: Install external tools
  tags:
    - intsall
    - core
    - external
    - dev
  block:
    - name: Install via curl
      ansible.builtin.shell: item
      loop: "{{ more_tools}}"
      tags:
        - go_install

    - name: Install with Go
      ansible.builtin.shell: go install {{ item }}
      loop: "{{ go_installs }}"
      tags:
        - go_install

    - name: Install with uvx
      ansible.builtin.shell: uv tool install {{ item }}
      loop: "{{ uv_installs }}"
      tags:
        - uv_install

