- name: flatpak present
  package:
    name: flatpak
    state: present
  tags:
    - install
    - flatpak

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - config
    - flatpak

- name: Include flatpak variables
  include_vars:
    file: ../vars/flatpak.yaml
  tags:
    - install
    - config
    - flatpak

- name: Install Flatpaks by category
  community.general.flatpak:
    name: "{{ item.value }}"
    state: present
    method: system
  loop: "{{ flatpaks | dict2items }}"
  loop_control:
    label: "{{ item.key }}" # Optional: Makes the output cleaner, showing the category name
  tags:
    - install
    - flatpak
