- name: Install Flatpak package manager
  become: true # Required for system package installation
  package:
    name: flatpak
    state: present
  tags:
    - flatpak
    - install

- name: Configure Flathub repository for Flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - flatpak
    - install

- name: Include flatpak variables
  include_vars:
    file: ../vars/flatpak.yaml
  tags:
    - install
    - flatpak

- name: Install Flatpak applications
  community.general.flatpak:
    name: "{{ item.value }}"
    state: present
    method: system
  loop: "{{ flatpaks | dict2items }}"
  loop_control:
    label: "{{ item.key }}" # Shows category name for better progress tracking
  tags:
    - install
    - flatpak
