- name: Install System Packages
  become: true
  package:
    name:
      - curl
      - wget
      - fzf
      - fd-find
      - ripgrep
      - tldr
      - vim
      - sd
      - xclip
      - wl-clipboard
  tags:
    - install
    - core

- name: Install Programming Languages
  become: true
  package:
    name:
      - lua5.1
      - golang
      - rust
      - node
      - gcc
      - gawk
      - sd
    status: lastest
  tags:
    - install
    - core

- name: Install Terminal UI
  become: true
  package:
    name:
      - tmux
      - lazygit
      - git-delta
      - bat
  tags:
    - install
    - core

- name: Install GitHub CLI
  hosts: your_servers
  become: true
  when: ansible_os_family = "Debian"

  tasks:
    - name: Download GitHub CLI keyring GPG
      shell: "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
      args:
        warn: false

    - name: Set permissions for GitHub CLI keyring
      file:
        path: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: go+r

    - name: Add GitHub CLI repository to sources.list.d
      lineinfile:
        path: /etc/apt/sources.list.d/github-cli.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        create: yes

    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install GitHub CLI
      apt:
        name: gh
        state: present

