- name: Nvidia Drivers and App
  become: true
  dnf:
    name:
      - akmod-nvidia
      - nvidia-settings
  tags:
    - install
    - RPM
    - Nvidia
  when: ansible_os_family == 'RedHat'

- name: Install Packages
  become: true
  package:
    - htop
    - toolbox
    - build-essential
    - moreutils
    - neofecth
    - cmake
    - libstdc++
    - xclip
    - wl-clipboard
  tags:
    - install
    - Fedora
    - core
  when: ansible_os_family == 'RedHat'

- name: Install Graphic UI
  become: true
  dnf:
    name:
      - dconf-editor
      - firefox
      - gnome-console
      - alacritty
  tags:
    - install
    - core
  when: ansible_os_family == 'RedHat'
