- name: flatpak present
  package:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Essential Flatpak
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.github.IsmaelMartinez.teams_for_linux
      - com.github.jeromerobert.pdfarranger
      - com.github.tchx84.Flatseal
      - com.google.Chrome
      - com.mattjakeman.ExtensionManager
      - com.spotify.Client
      - de.haeckerfelix.Fragments
      - com.valvesoftware.Steam
      - org.gnome.Decibels
      - org.mozilla.Thunderbird
      - org.onlyoffice.desktopeditors
      - org.videolan.VLC
    state: present
    method: system

- name: Install Creative Flatpak
  community.general.flatpak:
    name:
      - com.belmoussaoui.Decoder
      - com.github.huluti.Curtail
      - com.obsproject.Studio
      - fr.romainvigier.MetadataCleaner
      - io.gitlab.adhami3310.Converter
      - org.audacityteam.Audacity
      - org.darktable.Darktable
      - org.gimp.GIMP
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.inkscape.Inkscape
      - org.kde.krita
    state: present
    method: system

- name: Install Dev Flatpak
  community.general.flatpak:
    name:
      - com.getpostman.Postman
      - com.usebruno.Bruno
      - com.visualstudio.code
      - io.beekeeperstudio.Studio
      - io.gitlab.liferooter.TextPieces
    state: present
    method: system

- name: Install Gnome Dev Flatpak
  community.general.flatpak:
    name:
      - app.drey.Elastic
      - org.gnome.Builder
      - re.sonny.Workbench
    state: present
    method: system

- name: Install Misc Flatpak
  community.general.flatpak:
    name:
      - com.belmoussaoui.Obfuscate
      - com.github.alexhuntley.Plots
      - com.github.tenderowl.frog
      - io.github.alainm23.planify
      - info.febvre.Komikku
      - io.github.amit9838.mousam
      - io.github.mpobaschnig.Vaults
      - io.github.vikdevelop.SaveDesktop
      - org.bleachbit.BleachBit
      - org.gnome.gitlab.YaLTeR.Identity
      - org.gnome.gitlab.somas.Apostrophe
      - se.sjoerd.Graphs
      - org.torproject.torbrowser-launcher
    state: present
    method: system
