- name: flatpak present
  package:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install via flatpak
  community.general.flatpak:
    name:
      - com.obsproject.Studio
      - com.discordapp.Discord
      - com.getpostman.Postman
      - com.spotify.Client
      - com.github.huluti.Curtail
      - fr.romainvigier.MetadataCleaner
      - com.valvesoftware.Steam
      - org.darktable.Darktable
      - org.gimp.GIMP
      - org.gaphor.Gaphor
      - org.inkscape.Inkscape
    state: present
    method: system
