- name: Install Neovim
  become: true
  package:
    name: neovim
  tags:
    - install
    - neovim

- name: Get Packer
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
